### ISSUE TITLE
Proselint spits tons of error messages on anything that I try to run it on

### ISSUE THREAD

**Issue by skylerberg** [amperser/proselint#305] opened 2016-03-07 06:26 UTC
Here is the result on an empty file:
```
skyler@sib5:~/.proselint|→  proselint asdf
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
```

**Comment by stevenkaras** [comment] 2016-03-07 07:48
Ran into this when I tried to run with python 2.7 on Ubuntu 1404.

Running `proselint --i` printed errors for demo.md, but followed by about two screens of this error

**Comment by suchow** [comment] 2016-03-07 08:11
Thanks for the report, it's helpful because this one has been hard to figure out.

I believe this is a duplicate of #238, so I'm going to close this.

If anyone is interested in digging into this, it would be incredibly helpful — I can't reproduce it on my system, so it's hard for me to debug.

**Closed** 2016-03-07 08:11 UTC
Labels: duplicate

**Comment by richard-fairthorne** [comment] 2016-03-09 19:26
I've coded a fix. Just figuring out how to fork and send a pull request :D
